### ISSUE TITLE
Missing API values

### ISSUE THREAD

**Issue by kotobubu** [doej1367/HyBlockUtils#2]
I am using this app but i get this error when i am searching for someones stats, even my own stats, i can only see fairy souls and slayer lvl dungeons and armor not skill average and stuff

**Comment by kotobubu** [comment]
I am sorry this is invalid, its just that a player witch doesnt have the stuff gets this error, when i tried it on a good player it worked, but i still cant figure out whats its saying haha..

**Comment by doej1367** [comment]
1. If you got a bug, please also submit a screenshot so I can see for myself
2. I know the app is broken. I developed it over a year ago and back then it was working perfectly. Since then there were huge changes in the Hypixel API which broke quite a lot of stuff in the `ApiRequest` class and every class trying to get data from the returned JSON Objects. Many things in the Hypixel API are removed, added or in a completely different place now... don't know yet if I'll find the time to rework the whole thing to fix all of that. We'll see...

**Comment by doej1367** [comment]
> I am sorry this is invalid, its just that a player witch doesnt have the stuff gets this error, when i tried it on a good player it worked, but i still cant figure out whats its saying haha..

Now that I fixed the profile selector (didn't release that version yet), that broke when Hypixel removed the "last_login" value from profiles, I know what you mean. 

`<Error: missing api values!>` simply means that the app has no access to those values. One very common reason is that you've hidden those in your Skyblock island settings (accessable e.g. via Jerry). Hidden stats are default on every new island / profile you create.

**Comment by doej1367** [comment]
> `<Error: missing api values!>` i can only see fairy souls and slayer lvl dungeons and armor

Yup, that sounds a lot like hidden api stats. I'm going to close this issue for now. Also in version 1.0.5 a lot of 'outdated api problems' should be fixed now :)
